#!/bin/bash


WARNING=15
CRITICAL=5
CHECKED=0

send_notification() {
	notify-send -t 10000 -u critical "$1" "$2"
} 

while [ true ]; do
	sleep 1m

	CHARGING=$(cat /sys/class/power_supply/BAT0/status)

	if [ $CHARGING = "Charging" ]; then
		CHECKED=0
		continue
	fi

	BAT_LEVEL=$(cat /sys/class/power_supply/BAT0/capacity)

	if [ $BAT_LEVEL -le $CRITICAL ] && [ $CHECKED -le 1 ]; then
		send_notification 'Battery critical!' "Battery is at $BAT_LEVEL%\nPlease charge immediately!"
		CHECKED=2
	elif [ $BAT_LEVEL -le $WARNING ] && [ $CHECKED -eq 0 ]; then
		send_notification 'Battery warning!' "Battery is at $BAT_LEVEL%\nPlease charge soon!"
		CHECKED=1
	fi
done
