#!/bin/bash

TOTP=$(kdialog --inputbox "Pwease enter the 2FA UwU" --title "PWULL :3")

if [[ $? = 1 ]]; then
exit 1
fi

rclone sync protondrive:stuff/stuff2.kdbx $HOME/.local/stuff --protondrive-2fa=$TOTP && notify-send -a 'PWUSH1' $? &

rclone sync protondrive:stuff/stuff2\ 2.kdbx $HOME/.local/stuff --protondrive-2fa=$TOTP && notify-send -a 'PWUSH2' $?
